const q=id=>document.getElementById(id);
function tabs(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');q(b.dataset.tab).classList.add('active')})}
async function activeTab(){let [t]=await chrome.tabs.query({active:true,currentWindow:true});return t}
async function ensureOverlayOnActiveTab(){
 let t=await activeTab();if(!t?.id||!/^https?:/i.test(t.url||''))return false;
 try{
  const r=await chrome.scripting.executeScript({target:{tabId:t.id},func:()=>!!globalThis.__DLO_TRACKER_ACTIVE__});
  if(r?.[0]?.result)return true;
  await chrome.scripting.insertCSS({target:{tabId:t.id},files:['bet-content.css','fantasy-content.css']});
  await chrome.scripting.executeScript({target:{tabId:t.id},files:['parser.js','bet-content.js','fantasy-runtime.js']});
  return true;
 }catch(_){return false}
}
async function send(msg){let t=await activeTab();if(!t?.id)throw Error('No active tab.');try{return await chrome.tabs.sendMessage(t.id,msg)}catch(e){try{await chrome.scripting.insertCSS({target:{tabId:t.id},files:['fantasy-content.css']});await chrome.scripting.executeScript({target:{tabId:t.id},files:['fantasy-runtime.js']});return await chrome.tabs.sendMessage(t.id,msg)}catch(x){throw Error('Open an ESPN FantasyCast or Sleeper matchup in this tab, then try Sync again.')}}}
function renderFantasy(m){q('fTeams').textContent=m?`${m.myTeam}  ${Number.isFinite(m.myScore)?m.myScore.toFixed(1):'--'}  —  ${Number.isFinite(m.oppScore)?m.oppScore.toFixed(1):'--'}  ${m.oppTeam}`:'Not synced yet';let ps=(m?.players||[]).filter(p=>p.starter).slice(0,8);q('fRoster').innerHTML=ps.map(p=>`<div class="frow"><span>${p.side==='me'?'MY':'OPP'} · ${p.name}</span><b>${Number.isFinite(p.points)?p.points.toFixed(1):'--'}</b></div>`).join('')}
async function quickFantasySync(statusId='quickStatus'){const out=q(statusId);out.className='status';out.textContent='Syncing fantasy…';try{let r=await send({type:'DLO_FANTASY_SYNC'});if(!r?.ok)throw Error(r?.error||'Sync failed');renderFantasy(r.matchup);out.textContent=`✓ Fantasy: ${r.starters} starters · ${r.players} players`;return r}catch(e){out.className='status err';out.textContent=e.message;throw e}}
async function init(){tabs();await ensureOverlayOnActiveTab();await chrome.storage.local.set({betModuleEnabled:true,enabled:true,fantasyEnabled:true});let d=await chrome.storage.local.get({betModuleEnabled:true,enabled:true,fantasyEnabled:true,showOpponentTotal:true,showOpponentPlayers:true,showBenchPlayers:false,showFantasyTeamIcons:true,opponentUpdates:true,fantasyNotifyMode:'every',fantasyMatchup:null,appTheme:'espn'});document.body.dataset.dloTheme=d.appTheme||'espn';document.querySelectorAll('.themeBtn').forEach(b=>{b.classList.toggle('active',b.dataset.theme===(d.appTheme||'espn'));b.onclick=async()=>{const theme=b.dataset.theme;document.body.dataset.dloTheme=theme;document.querySelectorAll('.themeBtn').forEach(x=>x.classList.toggle('active',x===b));await chrome.storage.local.set({appTheme:theme})}});q('betEnabled').checked=d.betModuleEnabled!==false;q('fantasyEnabled').checked=d.fantasyEnabled!==false;q('fEnabled').checked=d.fantasyEnabled!==false;q('fOppTotal').checked=d.showOpponentTotal!==false;q('fOppPlayers').checked=d.showOpponentPlayers!==false;q('fBench').checked=d.showBenchPlayers===true;q('fTeamIcons').checked=d.showFantasyTeamIcons!==false;q('fOppUpdates').checked=d.opponentUpdates!==false;q('fNotify').value=d.fantasyNotifyMode||'every';renderFantasy(d.fantasyMatchup);
 q('betEnabled').onchange=()=>chrome.storage.local.set({betModuleEnabled:q('betEnabled').checked,enabled:q('betEnabled').checked});q('fantasyEnabled').onchange=()=>{q('fEnabled').checked=q('fantasyEnabled').checked;chrome.storage.local.set({fantasyEnabled:q('fantasyEnabled').checked})};q('fEnabled').onchange=()=>{q('fantasyEnabled').checked=q('fEnabled').checked;chrome.storage.local.set({fantasyEnabled:q('fEnabled').checked})};[['fOppTotal','showOpponentTotal'],['fOppPlayers','showOpponentPlayers'],['fBench','showBenchPlayers'],['fTeamIcons','showFantasyTeamIcons'],['fOppUpdates','opponentUpdates']].forEach(([id,key])=>q(id).onchange=()=>chrome.storage.local.set({[key]:q(id).checked}));q('fNotify').onchange=()=>chrome.storage.local.set({fantasyNotifyMode:q('fNotify').value});
 q('quickBets').onclick=()=>syncCopiedBets('quickStatus').catch(()=>{});q('quickFantasy').onclick=()=>quickFantasySync('quickStatus').catch(()=>{});
 q('fSync').onclick=async()=>{q('fStatus').className='status';q('fStatus').textContent='Syncing…';try{let r=await send({type:'DLO_FANTASY_SYNC'});if(!r?.ok)throw Error(r?.error||'Sync failed');renderFantasy(r.matchup);q('fStatus').textContent=`Synced ${r.starters} starters · ${r.players} players`;}catch(e){q('fStatus').className='status err';q('fStatus').textContent=e.message}};q('fTestGood').onclick=()=>send({type:'DLO_FANTASY_TEST',side:'me'}).catch(()=>{});q('fTestBad').onclick=()=>send({type:'DLO_FANTASY_TEST',side:'opp'}).catch(()=>{});
}
init();
